python3 ASTARTraslados.py ./ASTAR-tests/mapa01.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa01.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa02.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa02.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa03.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa03.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa04.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa04.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa05.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa05.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa06.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa06.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa07.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa07.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa08.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa08.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa09.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa09.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa10.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa10.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa11.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa11.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa12.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa12.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa13.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa13.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa14.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa14.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa15.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa15.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/mapa16.csv 1
python3 ASTARTraslados.py ./ASTAR-tests/mapa16.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/enunciado-reducido.csv 2
python3 ASTARTraslados.py ./ASTAR-tests/enunciado-reducido.csv 1
